BTC:
  outputs:
    dev:
      account: VAIPEWF-HRC85265
      database: BTC
      password: kWHM5x9tmjcTdkK
      role: ACCOUNTADMIN
      schema: DBT_GOPAL
      threads: 1
      type: snowflake
      user: bommalagopalrao8413
      warehouse: COMPUTE_WH
    dev2:
      account: VAIPEWF-HRC85265
      database: BTC
      password: kWHM5x9tmjcTdkK
      role: ACCOUNTADMIN
      schema: dbt_gopal_dev2
      threads: 1
      type: snowflake
      user: bommalagopalrao8413
      warehouse: COMPUTE_WH
    prod:
      account: VAIPEWF-HRC85265
      database: BTC
      password: kWHM5x9tmjcTdkK
      role: ACCOUNTADMIN
      schema: PROD
      threads: 1
      type: snowflake
      user: bommalagopalrao8413
      warehouse: COMPUTE_WH
  target: dev2
DBT_TRAINING:
  outputs:
    dev:
      account: vaipewf-hrc85265
      database: DBT_TRAININGS
      password: kWHM5x9tmjcTdkK
      role: accountadmin
      schema: TPCH_SF100
      threads: 1
      type: snowflake
      user: bommalagopalrao8413
      warehouse: MY_LARGEWH
  target: dev
ETH:
  outputs:
    dev:
      account: VAIPEWF-HRC85265
      database: ETH
      password: kWHM5x9tmjcTdkK
      role: accountadmin
      schema: DBT_ETH_GOPAL
      threads: 1
      type: snowflake
      user: bommalagopalrao8413
      warehouse: MY_LARGEWH
  target: dev
